language: java
jdk: oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: elvEm4sH0AQM3nL6Xvt2SbV4OYpzIeFPguTgV5cz7W/kdGxvpoum6GyP34bCq4tc2TM2mhoHHql9QR5yjN1NM+VvFv8xrQDbBXMuoJm8KGqVpOB/nZ/f74WaIX4+LOIv+jfy8M2zas/s99SHY/CvC1uCkzcoVDxjm/3jPCrrfzegE7kIcDelFVTP9QmhcCDZwCP/DHT+/vLEkaRTH0vjRVTgNP2fLRQouYGKgY0GDNLzIz7dujYP1AF+miQRyFAmAXDZYEk8IcaQ5kw1PmipH7TZPaLbqYEthRx0L4pgey5T3+mfZ208WK/xQCUMjv0k1fXdIP6XcmdabEFqWyWcQgUEnSazUw39q9kxTRTF4rj0fBB1jGBOzDa1nS57P02ztshWoWE4ImbnZK54dyqgXr4M3YHtI3kkwTU3N4WkKzjYpkyYMe1dZkgAuFwLMNToekY470zs0p4L4cjmAhOF5hJ3AN98X7U6uloJZ/suZ5riCVQVhbwmC8ayMlWJaJeXVDyjYnFNqw6fhynhl+qf0vPObVY4mjvlqofS/vCo179Rgl/c06/bjQ40sRA6395woxbz9eXUfbAuyOHc4k8FhV0B5dYbnfMqI23gVaTcEEhi0TF5dtT7Q6o9QNyFUc5CC+TWelkBJy1iX9VxZlvVjakZOkQia9oKXMuZZ/ehPqU=
  app: isapi-measures
